package com.huju.panda.test.vo;

import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

/**
 * Created by v_huju on 2018/2/2.
 */
public class IndexVo  implements Serializable {

    /**
     * 指标ID
     * 表字段 : kpi_index.id
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.id
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    @Id
    private Long id;

    /**
     *
     * 表字段 : kpi_index.status_code
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.status_code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String statusCode;

    /**
     * 指标CODE
     * 表字段 : kpi_index.code
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String code;

    /**
     * 指标名称
     * 表字段 : kpi_index.name
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.name
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String name;

    /**
     * 组织ID
     * 表字段 : kpi_index.org_id
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.org_id
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private Long orgId;

    /**
     * 指标类型(静态/动态)
     * 表字段 : kpi_index.index_type
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.index_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String indexType;

    /**
     * 数据类型/计算方式(数值型、多行文本、打分项、日期、附件、公式、sql、脚本)
     * 表字段 : kpi_index.data_type
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.data_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String dataType;

    /**
     * 动态数据格式
     * 表字段 : kpi_index.dynamic_data_type
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.dynamic_data_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String dynamicDataType;

    /**
     * 是否存在默认值  Y/N
     * 表字段 : kpi_index.default_flag
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.default_flag
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String defaultFlag;

    /**
     * 默认值
     * 表字段 : kpi_index.default_val
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.default_val
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String defaultVal;

    /**
     * 是否自定义数据格式  Y/N
     * 表字段 : kpi_index.format_flag
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.format_flag
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String formatFlag;

    /**
     * 数据格式
     * 表字段 : kpi_index.format_val
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.format_val
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String formatVal;

    /**
     * 查找集CODE
     * 表字段 : kpi_index.lookup_code
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.lookup_code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String lookupCode;

    /**
     * sql
     * 表字段 : kpi_index.sql_desc
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.sql_desc
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String sqlDesc;

    /**
     * script脚本
     * 表字段 : kpi_index.script_desc
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.script_desc
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String scriptDesc;

    /**
     * 公式
     * 表字段 : kpi_index.expression
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.expression
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String expression;

    /**
     * 备注
     * 表字段 : kpi_index.remarks
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.remarks
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String remarks;

    /**
     * 指标计算时间
     * 表字段 : kpi_index.calc_time
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.calc_time
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String calcTime;

    /**
     * 扩展字段1
     * 表字段 : kpi_index.attribute1
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.attribute1
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String attribute1;

    /**
     * 扩展字段2
     * 表字段 : kpi_index.attribute2
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.attribute2
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String attribute2;

    /**
     * 扩展字段3
     * 表字段 : kpi_index.attribute3
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.attribute3
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String attribute3;

    /**
     * 扩展字段4
     * 表字段 : kpi_index.attribute4
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.attribute4
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String attribute4;

    /**
     * 扩展字段5
     * 表字段 : kpi_index.attribute5
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.attribute5
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String attribute5;

    /**
     *
     * 表字段 : kpi_index.icon
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.icon
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String icon;

    /**
     * 运算规则
     * 表字段 : kpi_index.index_rule
     */
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kpi_index.index_rule
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private String indexRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kpi_index
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.id
     *
     * @return the value of kpi_index.id
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.id
     *
     * @param id the value for kpi_index.id
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.status_code
     *
     * @return the value of kpi_index.status_code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.status_code
     *
     * @param statusCode the value for kpi_index.status_code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.code
     *
     * @return the value of kpi_index.code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.code
     *
     * @param code the value for kpi_index.code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.name
     *
     * @return the value of kpi_index.name
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.name
     *
     * @param name the value for kpi_index.name
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.org_id
     *
     * @return the value of kpi_index.org_id
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.org_id
     *
     * @param orgId the value for kpi_index.org_id
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.index_type
     *
     * @return the value of kpi_index.index_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.index_type
     *
     * @param indexType the value for kpi_index.index_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setIndexType(String indexType) {
        this.indexType = indexType == null ? null : indexType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.data_type
     *
     * @return the value of kpi_index.data_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.data_type
     *
     * @param dataType the value for kpi_index.data_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.dynamic_data_type
     *
     * @return the value of kpi_index.dynamic_data_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getDynamicDataType() {
        return dynamicDataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.dynamic_data_type
     *
     * @param dynamicDataType the value for kpi_index.dynamic_data_type
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setDynamicDataType(String dynamicDataType) {
        this.dynamicDataType = dynamicDataType == null ? null : dynamicDataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.default_flag
     *
     * @return the value of kpi_index.default_flag
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getDefaultFlag() {
        return defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.default_flag
     *
     * @param defaultFlag the value for kpi_index.default_flag
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setDefaultFlag(String defaultFlag) {
        this.defaultFlag = defaultFlag == null ? null : defaultFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.default_val
     *
     * @return the value of kpi_index.default_val
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getDefaultVal() {
        return defaultVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.default_val
     *
     * @param defaultVal the value for kpi_index.default_val
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setDefaultVal(String defaultVal) {
        this.defaultVal = defaultVal == null ? null : defaultVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.format_flag
     *
     * @return the value of kpi_index.format_flag
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getFormatFlag() {
        return formatFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.format_flag
     *
     * @param formatFlag the value for kpi_index.format_flag
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setFormatFlag(String formatFlag) {
        this.formatFlag = formatFlag == null ? null : formatFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.format_val
     *
     * @return the value of kpi_index.format_val
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getFormatVal() {
        return formatVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.format_val
     *
     * @param formatVal the value for kpi_index.format_val
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setFormatVal(String formatVal) {
        this.formatVal = formatVal == null ? null : formatVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.lookup_code
     *
     * @return the value of kpi_index.lookup_code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getLookupCode() {
        return lookupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.lookup_code
     *
     * @param lookupCode the value for kpi_index.lookup_code
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setLookupCode(String lookupCode) {
        this.lookupCode = lookupCode == null ? null : lookupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.sql_desc
     *
     * @return the value of kpi_index.sql_desc
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getSqlDesc() {
        return sqlDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.sql_desc
     *
     * @param sqlDesc the value for kpi_index.sql_desc
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setSqlDesc(String sqlDesc) {
        this.sqlDesc = sqlDesc == null ? null : sqlDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.script_desc
     *
     * @return the value of kpi_index.script_desc
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getScriptDesc() {
        return scriptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.script_desc
     *
     * @param scriptDesc the value for kpi_index.script_desc
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setScriptDesc(String scriptDesc) {
        this.scriptDesc = scriptDesc == null ? null : scriptDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.expression
     *
     * @return the value of kpi_index.expression
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getExpression() {
        return expression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.expression
     *
     * @param expression the value for kpi_index.expression
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setExpression(String expression) {
        this.expression = expression == null ? null : expression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.remarks
     *
     * @return the value of kpi_index.remarks
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.remarks
     *
     * @param remarks the value for kpi_index.remarks
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.calc_time
     *
     * @return the value of kpi_index.calc_time
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getCalcTime() {
        return calcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.calc_time
     *
     * @param calcTime the value for kpi_index.calc_time
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setCalcTime(String calcTime) {
        this.calcTime = calcTime == null ? null : calcTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.attribute1
     *
     * @return the value of kpi_index.attribute1
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.attribute1
     *
     * @param attribute1 the value for kpi_index.attribute1
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1 == null ? null : attribute1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.attribute2
     *
     * @return the value of kpi_index.attribute2
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.attribute2
     *
     * @param attribute2 the value for kpi_index.attribute2
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2 == null ? null : attribute2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.attribute3
     *
     * @return the value of kpi_index.attribute3
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.attribute3
     *
     * @param attribute3 the value for kpi_index.attribute3
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3 == null ? null : attribute3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.attribute4
     *
     * @return the value of kpi_index.attribute4
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.attribute4
     *
     * @param attribute4 the value for kpi_index.attribute4
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4 == null ? null : attribute4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.attribute5
     *
     * @return the value of kpi_index.attribute5
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.attribute5
     *
     * @param attribute5 the value for kpi_index.attribute5
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5 == null ? null : attribute5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.icon
     *
     * @return the value of kpi_index.icon
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.icon
     *
     * @param icon the value for kpi_index.icon
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kpi_index.index_rule
     *
     * @return the value of kpi_index.index_rule
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public String getIndexRule() {
        return indexRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kpi_index.index_rule
     *
     * @param indexRule the value for kpi_index.index_rule
     *
     * @mbggenerated Tue Nov 14 11:42:12 CST 2017
     */
    public void setIndexRule(String indexRule) {
        this.indexRule = indexRule == null ? null : indexRule.trim();
    }

    /**
     * 创建时间
     * 表字段 : creation_date
     */
    private Date creationDate;

    /**
     * 创建人
     * 表字段 : created_by
     */
    private String createdBy;

    /**
     * 最后更新时间
     * 表字段 : last_update_date
     */
    private Date lastUpdateDate;

    /**
     * 最后更新人
     * 表字段 : last_updated_by
     */
    private String lastUpdatedBy;

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public String getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    public void setLastUpdatedBy(String lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }
}
